Add a Packet struct to represent a packet.
ataffanel/crazyflie-link-rs pull request #2
Opened 2021-03-15 10:51 UTC by jonasdn

2021-03-16 09:19 UTC, ataffanel requested changes
Looks good! The only problem I see is the handling of the 2 link-reserved bit that is not consistent with the current implementation.

Either the bandwidth example needs to be fixed or the reserved bits should be set to 0. I would go for setting the bits to 0, any reason you set them to 1?

2021-03-16 09:19 UTC, ataffanel commented on crazyflie-link/src/packet.rs
> +        //  ... bit 3 and 4 is legacy and set to 1 ...
Bit 3-4 are "Link-reserved". For the radio link they are used for flow control, on the other links they are unused. If set to "11", it breaks the benchmark example (see above).

The current implementation was [setting both reserved bit to 0](https://github.com/ataffanel/crazyflie-link-rs/blob/7d2ead8415b0e549315dc2d165a474f020b2d435/crazyflie-link/src/connection.rs#L219) when receiving a packer, we should likely keep them at 0.

2021-03-16 09:19 UTC, ataffanel commented on crazyflie-link/examples/benchmark.rs
> +                if packet.get_header() == 0xf0 {
Likely broken since bits 3 and 4 cannot be 0 anymore (see bellow).

Should likely be replaced by a test on port/channel anyway?

2021-03-16 09:56 UTC, jonasdn commented
> Looks good! The only problem I see is the handling of the 2 link-reserved bit that is not consistent with the current implementation.
> 
> Either the bandwidth example needs to be fixed or the reserved bits should be set to 0. I would go for setting the bits to 0, any reason you set them to 1?

I think they were set to 1 in the `CRTPPacket` class in the python lib:
```
        # The two bits in position 3 and 4 needs to be set for legacy
        # support of the bootloader
        self.header = header | 0x3 << 2
```

2021-03-16 10:02 UTC, jonasdn commented
I added a commit to keep the link-reserved bits at zero

2021-03-16 10:45 UTC, jonasdn commented
I used Packet::new(0xF .. in `benchmark.rs` now, is the ::from_header still needed you think?

2021-03-17 07:43 UTC, ataffanel approved these changes

2021-03-17 07:47 UTC, ataffanel commented
> I used Packet::new(0xF .. in `benchmark.rs` now, is the ::from_header still needed you think?

In a way, the header in raw form should never be needed, a CRTP packet is ```(port, channel, payload)```, the wire-format is just an implementation detail. That said, we have used the radio wire-format everywhere so it does not hurt to expose it.

Thanks for the PR! I am merging it.

2021-03-17 07:47 UTC, merged